exp_name: baseline2
description: baseline+augmentation
Global:
  epoch_num: 300
  output_dir: ./output/
  validation_every_n_epochs: 5
  num_classes: 8
  weights: /ssd/xuchenjie/projects/cervical/output/baseline1/models/rsna-epoch=139-val_loss=0.514.ckpt

Model:
  architecture: DenseNet
  activation: Sigmoid
  input_size: !!python/tuple
  - 80
  - 224
  - 224

Loss:
  name: CustomLoss

Optimizer:
  name: Adam
  lr: 0.00001
  beta1: 0.9
  beta2: 0.999

Lr_scheduler:
  name: cosine
  
#####data
Dataset:
    dataset_dir: /ssd/xuchenjie/projects/cervical/datasets
    test_size: 0.2
    image_dir: train_pt
    anno_path: train.csv

TrainReader:
  batch_size: 16
  num_workers: 6
  shuffle: false
  drop_last: false
ValReader:
  batch_size: 16
  num_workers: 6
  shuffle: false
  drop_last: false
TestReader:
  batch_size: 16